version: '3'
services:
  consul:
    container_name: "consul"
    image: "consul"
    command: "agent -server -bind=127.0.0.1 -bootstrap-expect=1 -ui"
    network_mode: "host"
  #  ports:
  #  - "8400:8400"
  #  - "8500:8500"
  #  - "8600:53"
    volumes:
    - "consul:/consul/data"
  vault:
    container_name: "vault"
    image: "vault"
    network_mode: "host"
    cap_add:
    - IPC_LOCK
    command: server
    environment:
    - 'VAULT_ADDR=http://127.0.0.1:8200'
    - 'VAULT_LOCAL_CONFIG={"backend": 
                            {"consul": {
                              "address": "127.0.0.1:8500", 
                              "path": "vault/", 
                              "advertise_addr": "http://127.0.0.1"
                              }
                            },
                          "ui": "true",
                          "listener":{
                              "tcp":{
                                "address": "127.0.0.1:8200", 
                                "tls_disable": 1
                              }
                            }
                          }' 
    


volumes:
  consul:
